[project]
name = "increment"
version = "0.1.0"
description = "Just experiment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blacksheep>=2.0.8",
    "blacksheep-cli>=0.0.4",
    "greenlet>=3.1.1",
    "isort>=6.0.1",
    "pre-commit>=4.1.0",
    "sqlalchemy>=2.0.38",
]

[tool.isort]
profile = "black"